#!/bin/bash
tmux start-server\; has-session -t android_deck 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /Users/glynch/code/android/deck_around

  # Run pre command.
  

  # Create the session and the first window.
  TMUX= tmux new-session -d -s android_deck -n java_editor


  # Create other windows.
  tmux new-window -c /Users/glynch/code/android/deck_around -t android_deck:1 -n xml_editor
  tmux new-window -c /Users/glynch/code/android/deck_around -t android_deck:2 -n consoles
  tmux new-window -c /Users/glynch/code/android/deck_around -t android_deck:3 -n logs
  tmux new-window -c /Users/glynch/code/android/deck_around -t android_deck:4 -n scratch


  # Window "java_editor"
  
  # tmux send-keys -t android_deck:0.0 '' C-m
  tmux send-keys -t android_deck:0.0 emacsclient\ -t\ ./src/ C-m

  tmux splitw -t android_deck:0
  tmux select-layout -t android_deck:0 main-vertical
  
  # tmux send-keys -t android_deck:0.1 '' C-m
  tmux send-keys -t android_deck:0.1 ant\ debug\ install C-m

  tmux select-layout -t android_deck:0 main-vertical

  tmux select-pane -t android_deck:0.0

  # Window "xml_editor"
  
#  tmux send-keys -t android_deck:1.0 '' C-m
  tmux send-keys -t android_deck:1.0 emacsclient\ -t \ ./res/layout/ C-m

  tmux splitw -t android_deck:1
  tmux select-layout -t android_deck:1 even-horizontal
  
  # tmux send-keys -t android_deck:1.1 '' C-m
  tmux send-keys -t android_deck:1.1 emacsclient\ -t\ ./res/values/strings.xml C-m

  tmux select-layout -t android_deck:1 even-horizontal

  tmux select-pane -t android_deck:1.0

  # Window "consoles"
  
  #tmux send-keys -t android_deck:2.0 '' C-m
  tmux send-keys -t android_deck:2.0 git\ pull C-m

  tmux splitw -t android_deck:2
  tmux select-layout -t android_deck:2 even-vertical
  
  # tmux send-keys -t android_deck:2.1 '' C-m

  tmux select-layout -t android_deck:2 even-vertical

  tmux select-pane -t android_deck:2.0

  # Window "logs"
  
  tmux send-keys -t android_deck:3 adb\ logcat C-m

  # Window "scratch"
  
  tmux send-keys -t android_deck:4 emacsclient\ -t C-m

  tmux select-window -t 0
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t android_deck
else
  tmux -u switch-client -t android_deck
fi
